services:
  access-granted:
    image: ghcr.io/mrjustreborn/access-granted/access-granted:dev
    build:
      context: ./src
      dockerfile: Dockerfile
      platforms:
        - linux/amd64
        - linux/arm64
    container_name: access-granted
    ports:
      - "5000:5000"
    restart: unless-stopped
    volumes:
      - "./src/data:/app/data"
    env_file:
      - "./env/dev.env"